### ISSUE TITLE
How to convert results to a string array?

### ISSUE THREAD

**Issue by Broham** [juliangruber/go-intersect#1]
I created the function below using this package:

```
func mergeResults(current, newData []string) (data []string) {
	if len(current) == 0 {
		return newData
	} else {
		return intersect.Hash(current, newData).([]string)
	}
}
```

This compiles, but when I hit my `else` statement, the following error is thrown:
`interface conversion: interface {} is []interface {}, not []string`

How can I return the results of the intersect as a string array?

**Comment by juliangruber** [comment]
https://stackoverflow.com/a/44027953
