### ISSUE TITLE
Semver release

### ISSUE THREAD

**Issue by loafoe** [juliangruber/go-intersect#2]
Possible to create a semver (v1.0.0) release of this library?

**Comment by juliangruber** [comment]
Sure, but I've never released a go library before :D Can you tell me how you do that?

**Comment by loafoe** [comment]
@juliangruber Just add `v1.0.0` tag to the GIT repo :-)

The new module support in Go 1.11+ will then recognise it, jobs done!

**Comment by juliangruber** [comment]
done! and thanks for showing me how that works
