### ISSUE TITLE
Implicitly return slice/array

### ISSUE THREAD

**Issue by cmin764** [juliangruber/go-intersect#4]
Is there any obvious reason for which the intersection returns an `interface{}` instead of `[]interface{}`? I think each time we do an intersection we expect to end up with an array/slice and not manually make that conversion each time.
Maybe I'm missing some casting edge-cases where this generic response makes sense.

**Comment by juliangruber** [comment]
Good point, I don't think it needs to be `interface{}`. Do you want to try this in a PR?

**Comment by cmin764** [comment]
Yes, how about this: https://github.com/juliangruber/go-intersect/pull/5 ?
